### PR TITLE
fix: improve loading performance of individual highlight

### PR DESCRIPTION
**Pull request by brandonroberts**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [x] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

- Adds direct link to OpenGraph image on individual highlight
- Removes extra requests from SSR request for individual highlight
- Fixes logic with selecting repo filters and opening individual highlights

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Review by OgDev-01 — APPROVED** [review]

**Comment by bdougie** [comment]
I had trouble QAing this. created a video

https://github.com/open-sauced/insights/assets/5713670/64455f93-2e64-4847-90f9-7b5751d43b04

**Comment by brandonroberts** [comment]
> https://deploy-preview-1349--oss-insights.netlify.app

Interesting. This happens on current `beta` also without these changes, so I'll take into that also

**Review by jpmcb — COMMENTED** [review]
Not sure if this is related, but the follow button's style doesn't look quite right to me on the beta deployment:

Screenshot 2023-07-13 at 10 52 05 AM

(notice how the follow button looks too wide and spills over to the left compared to the rest of the column)

On the live hightlights page, the alignment looks correct:

Screenshot 2023-07-13 at 10 52 26 AM

**Comment by brandonroberts** [comment]
@bdougie @jpmcb should be good to go now.

- Feed loads without issues
- Individual Highlights pop up from clicking on one and fresh page reload
- Repo filters are applied when clicked
- Follow button in dropdown menu is aligned correctly

**Review by jpmcb — APPROVED** [review]
Lookin good!!!!! 🍕

**Review by bdougie — APPROVED** [review]

**Pull request merged**
