### PR TITLE
fix: Deleted page button changed to delete highlight

### LINKED ISSUE #1382: Feature: Change "Delete page" to "Delete highlight" on highlights feed
### Type of feature

🍕 Feature

### Current behavior

Currently, when editing a highlight, it says "Delete page"

Screenshot 2023-07-17 at 10 15 56 AM

which is abit confusing to me (since I won't be deleting the whole Insights page! Just a single post).

### Suggested solution

Maybe instead it should say "Delete Highlight"? See below (edited in browser via web dev console:

Screenshot 2023-07-17 at 10 18 13 AM

Curious what others think or if this makes sense!

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by TylerSmith2614**
## Description
Changed highlight button to say "Delete Highlight" instead of "Delete Page" when editing a highlight.
image

Closes #1382

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [x] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Review by jpmcb — APPROVED** [review]
LGTM!

Closes #1382

**Comment by OgDev-01** [comment]
Thanks for taking this on @TylerSmith2614 🍕 . You can link this PR to the issue ticket by adding  `Closes #issueNumber` where in this case the issue ticket number is #1382 . doing this will enable automated closing of the issue ticket as completed once this PR is merged 👍

**Review by NsdHSO — APPROVED** [review]
LGTM, except for the mentions made by colleagues

**Review by bdougie — APPROVED** [review]
Please link the issue

**Pull request merged**
