### PR TITLE
fix: display input error message when entering highlight

### PR DESCRIPTION
**Pull request by parmishh**
Fix for displaying correct input error message 
https://github.com/open-sauced/insights/issues/1055

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
Fix for displaying correct input error message 
https://github.com/open-sauced/insights/issues/1055

## Related Tickets & Documents
#1055

## Mobile & Desktop Screenshots/Recordings

image

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by parmishh** [comment]
changes for error message

hhhhhhhhhh

**Comment by brandonroberts** [comment]
@parmishh the error message could be different than the one provided. I would suggest getting the error messages array from the response, taking the first one, and displaying that in the toast alert.

**Comment by takanome-dev** [comment]
@parmishh is there anything you need help with to get this merged?

**Comment by parmishh** [comment]
@takanome-dev I was little busy last week. I will fix this issue by end of this week🚀

**Pull request closed without merging**
