### PR TITLE
refactor: use Partial instead of extend

### LINKED ISSUE #878: Bug: duplicated types
### Describe the bug

Some types that we use in the database are being extended by other partials rather than using actual `Partial<Type>`

### Steps to reproduce

look for `UserResponse` or similar ` extends Db/Gh` instances in the code

### Affected services

insights.opensauced.pizza

### Platforms

_No response_

### Browsers

_No response_

### Environment

_No response_

### Additional context

backend and github types require consolidation

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by Deadreyo**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [x] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

Replaced interface extended from DbUser to be type of Partial from DbUser

## Related Tickets & Documents

closes #878 
## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by Deadreyo** [comment]
@0-vortex is this what you mean?

**Comment by Deadreyo** [comment]
Can't be the intended change. Will revert once I understand what needs to be done.

**Comment by 0-vortex** [comment]
> Can't be the intended change. Will revert once I understand what needs to be done.

It is, pretty much, the ticket is more about chasing down the backend -> frontend type inconsistencies, UserResponse just being one of them used in 2 files, which can also be partial'd.

Since most of the backend types are actually provided by GitHub resources, letting the frontend be too loose with data types is not desired. Best case scenario is "data" interfaces being clearly separated from "component props" interfaces, at the moment some of them are mixed and diverging from the actual data source :<

**Comment by Deadreyo** [comment]
> > Can't be the intended change. Will revert once I understand what needs to be done.
> 
> It is, pretty much, the ticket is more about chasing down the backend -> frontend type inconsistencies, UserResponse just being one of them used in 2 files, which can also be partial'd.
> 
> Since most of the backend types are actually provided by GitHub resources, letting the frontend be too loose with data types is not desired. Best case scenario is "data" interfaces being clearly separated from "component props" interfaces, at the moment some of them are mixed and diverging from the actual data source :<

Hmm. After I've made the current change and did the `Partial`, conditionals will have to be added everywhere the `UserReponse` was used in (deploy failed because of that) since we moved from required props to optional props with `Partial`. If we are sure that all the data in the interface are always returned, would we really need to put Partial and turn them optional?

For the specific case of `UserResponse`, I think just assigning the type as `type UserResponse = DbUser` is more practical than `Partial<DbUser>` to not add unnecessary optionals if not needed

**Comment by Deadreyo** [comment]
@0-vortex Could you enlighten me more plz on this topic? Would love to learn and gain more knowledge from your point of view

**Comment by 0-vortex** [comment]
> @0-vortex Could you enlighten me more plz on this topic? Would love to learn and gain more knowledge from your point of view

Sure, just put this PR on hold until https://github.com/open-sauced/api.opensauced.pizza/pull/127 is merged in, it will fix numbers and start making the codebase reusable in other smaller backends we might need to set up fast(er) in the future, like the social graph endpoint, and, with a bit more tweaking, even the frontend.

For the frontend improvement we might have to wait due to priorities, but let me tl;dr: the boring parts, having sunset the GitSense API, we have no more type collisions across our primary areas of interest, those being the [Insights frontend](https://github.com/open-sauced/insights) and the [API backend](https://github.com/open-sauced/api.opensauced.pizza), meaning that we can start exploring ways to reduce time wasted doing "type management" in the frontend by removing the GitSense and Database types altogether while installing them from a `types.d.ts` generated file from the API library containing all our types (a couple of issues here, the backend is not a library to be used right away like that, we are just decoupling usages and consolidating all the types in that repo right now, this refactor would have to wait for that moment in time to make proper use our our `Partial` and `DeepPartial` discussion).

The above would be the "fun" part if we ever get to it. From a very realistic perspective, the focus of this issue and PR will likely be changed towards adjusting the current types with minimal effort, because, don't know if you remember that issue where the backend was throwing numbers as strings:

Screenshot 2023-03-19 at 12 11 42

Well, surprise!!! 🥳 It's coming to beta in that PR mentioned at the top! 🍕 

Might sound like work, but because we were dealing with strings, it's going to be a "delete" type of refactoring where we can drop some of the number conversions, and, there are a lot of them out there! 😅

**Comment by brandonroberts** [comment]
Marking as blocked for now

**Comment by brandonroberts** [comment]
Can we close this for now? Doesn't seem to be anything actionable that can be done

**Comment by 0-vortex** [comment]
> Can we close this for now? Doesn't seem to be anything actionable that can be done

Agreed, we can soon get all of this from the backend api package and use partial and composition to define component requirements! 🍕

**Pull request closed without merging**
