### PR TITLE
fix: long names spacing in top contributors card

### LINKED ISSUE #1518: bug: Long names in top contributors mess up spacing on small screens.
bug: Long names in top contributors mess up spacing on small screens.

I noticed a weird side effect. I did see this get reported elsewhere. OK to have it addressed on another PR

My suggestion is to add truncation when the width is adjusted.

Screen Shot 2023-08-07 at 4 46 56 PM

_Originally posted by @bdougie in https://github.com/open-sauced/insights/issues/1516#issuecomment-1668759551_

### PR DESCRIPTION
**Pull request by RitaDee**
## Description

On smaller screens, a formatting issue arises within the "Top Contributors" section where long names disrupt the intended spacing, leading to an unsightly visual presentation. This bug undermines the overall user experience and aesthetic appeal of the application. This PR implements a responsive fix that ensures the proper alignment and spacing of contributor names, even when they are exceptionally long. 

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #1518 

## Mobile & Desktop Screenshots/Recordings

Before:

image

After:

https://github.com/open-sauced/insights/assets/106407013/22ca0961-4760-43c7-9ae6-abf7e027dc4b

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by bdougie** [comment]
This looks good, but it seems there are unrelated changelog updates that will need be reverted. This commit introduced the changes https://github.com/open-sauced/insights/pull/1520/commits/cf9c395b2d8f38de567fbd3683229999c04f8f38

**Comment by RitaDee** [comment]
Hey @bdougie, the change has been implemented. Thank you

**Comment by RitaDee** [comment]
Hey @bdougie, the change has been implemented. Thank you

**Comment by bdougie** [comment]
> Hey @bdougie, the change has been implemented. Thank you

The CHANGELOG changes should not be in this PR. 

Screen Shot 2023-08-08 at 3 36 15 PM

**Comment by RitaDee** [comment]
@bdougie, I can't tell why I have too many files changed. Any clue on why this occurred and suggestions on the fix?

**Comment by bdougie** [comment]
Delete the file locally and then run the checkout command I mentioned. 

The goal is reset the file to what is currently on beta. Once we revert those changes we can merge this PR.

**Comment by takanome-dev** [comment]
You might also want to skip precommit hooks, I ran into this when trying to revert the CHANGELOG file, see https://github.com/open-sauced/insights/pull/1478#issuecomment-1668169802

**Comment by bdougie** [comment]
@RitaDee There are now even more unrelated changes in the commits.

As @takanome-dev mention there is most likely something you are doing causing these extra commits to appear. 

Can you join us in the opensauced contributor chat channel in the discord to debug this?

https://discord.gg/opensauced

I will also close this PR. It is still able to be repaired.

**Comment by RitaDee** [comment]
Okay @bdougie, thank you for your feedback.

I'm already a member of the opensauced contributor chat channel on Discord and I appreciate your invitation to debug this situation together. 

To keep my branch up to date with changes from the beta branch, I typically use git pull to grab the latest updates. I'll take a closer look to ensure that there aren't any actions on my part causing the unrelated commits.

Thank you for your understanding and for considering a synchronous conversation to address this issue.

**Pull request closed without merging**
