### PR TITLE
feat: implement repo suggestions in create insight page

### LINKED ISSUE #711: Feature: Add a Suggested Repos section when creating new insight page
### Type of feature

🍕 Feature

### Current behavior

As suggested by @bdougie , a suggested repos section in `/hub/insights/new` that is based on the user's organization and have suggestions for repos to be added to the page.

### Suggested solution

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by Deadreyo**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
- Extends on the Repo Suggestions List component
- Inserts it in Create Insight Page
- Adds 3 static suggestions to it

## Related Tickets & Documents

closes #711
## Mobile & Desktop Screenshots/Recordings
image
image

## Added tests?

- [x] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by Deadreyo** [comment]
I've noticed that we have 2 almost identical components: `suggested-repo` and `repository-result`.

**Review by bdougie — CHANGES_REQUESTED** [review]
disregard the previous "requested changes." I responded to the wrong PR.

**Review by bdougie — APPROVED** [review]
Commented on the wrong PR before. This works, just need to work on this next. https://github.com/open-sauced/insights/issues/1001

**Review by 0-vortex — APPROVED** [review]
LGTM! 👍

**Review by OgDev-01 — APPROVED** [review]
🍕

**Pull request merged**
