### PR TITLE
fix: refactor notification username retrieval and display logic

### LINKED ISSUE #1529: Bug: Avatar is either not shown or is not the user
### Describe the bug

I opened the notification and the avatars of the same user are either empty or not the user.

#### Screenshot
 
avatar

(I'm sure the first avatar is not @BekahHW 😁) 

### Steps to reproduce

1. Click the notification icon.
2. See the avatars of the users.

### Browsers

Chrome

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by takanome-dev**
## Description

This PR refactors the logic for retrieving and displaying the username in the notifications component. 

- Added a new function `getNotificationUsername` which returns the username based on the notification type.
- Updated the avatarURL and username display logic to use the `getNotificationUsername` function.
- Removed the unused `username` variable and related code.
- Improved code readability and maintainability.

This change ensures that the correct username is displayed for each notification type and improves the overall code structure.

_Generated using [OpenSauced](https://opensauced.ai/)._

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [x] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #1529 
## Mobile & Desktop Screenshots/Recordings

Before

highlight-notif-reactions-before

After

highlight-notif-reactions-after

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by brandonroberts** [comment]
@takanome-dev this is not the solution we want as we can get this data from the API, and not base it off splitting up the message. 

https://github.com/open-sauced/api/pull/248 will have a proper fix for adding usernames

**Comment by brandonroberts** [comment]
@takanome-dev I should be able to click on each notification and it take me to the correct page

- User followed you -> link to user profile (meta_id is username)
- User created a highlight -> link to highlight (meta_id is highlight_id)
- User reacted to your highlight -> link to highlight (meta_id is highlight_id)

**Comment by takanome-dev** [comment]
> I see its linked to the username. Let's make it the entire text, and make the avatar link to the user profile

@brandonroberts done :+1:

**Review by jpmcb — APPROVED** [review]

**Comment by takanome-dev** [comment]
> @takanome-dev I don't see a link for the `highlight_created` notifications. Will you add that to the `get-notification-url` utility function?

Did it :sweat_smile:

**Review by brandonroberts — APPROVED** [review]

**Pull request merged**
