### PR TITLE
fix: Improved the user experience of the highlights input form

### LINKED ISSUE #1354: Bug: Improve User Experience of the Highlight Input form
## Description

Currently, there is a Highlight Input form with a Title and Description field. The Description field is hidden by default, leaving only the Title field visible. On clicking the Title field, the Description field toggles its display. However, in the current implementation, even if the Description field already contains content, clicking the Title field still toggles the Description field, which may lead to a suboptimal user experience. When a user fills in the Description field with content and then clicks the Title field, the Description field is hidden, requiring an additional click on the Title field to toggle the Description field and allow further editing of its content. This behavior can be confusing and inefficient for users.

## Demo

[screencast-insights.opensauced.pizza-2023.07.14-14_49_45.webm](https://github.com/open-sauced/insights/assets/25631971/e29a6c3b-d5ce-49c1-9170-b9126b19b579)

## Proposed Solution

To enhance the user experience, it is suggested to update the behavior of the Title field so that it conditionally hides the Description field only when the Description field has zero content. This way, if the Description field already contains content, clicking the Title field will not hide the Description field, allowing users to seamlessly edit or modify the existing content in the Description field without additional clicks.

## Steps to Implement

1. Update the code responsible for toggling the display of the Description field when clicking the Title field.
2. Introduce a condition to check if the Description field contains content.
3. If the Description field has content, do not toggle its display when the Title field is clicked.
4. If the Description field is empty, proceed with the current behavior of toggling its display when the Title field is clicked.

## Acceptance Criteria

- The Title field should conditionally hide the Description field based on its content.
- If the Description field has content, clicking the Title field should not hide the Description field.
- If the Description field is empty, clicking the Title field should toggle the display of the Description field.

## Additional Notes

- Consider updating any relevant documentation or user guides to reflect the updated behavior of the Title field.

Please address this issue to improve the user experience of the Highlight Input form.

### Steps to reproduce

1. Open the application or page containing the Highlight Input form.
2. Locate the Title field of the form.
3. Initially, observe that only the Title field is visible, and the Description field is hidden.
4. Click on the Title field to toggle the display of the Description field.
5. Note that the Description field becomes visible, allowing you to enter or edit its content.
6. Enter some text or content into the Description field.
7. Once the Description field contains content, click on the Title field again.
8. Notice that, in the current implementation, the Description field still gets hidden, even though it already has content.
9. To reveal the Description field again, click on the Title field once more.
10. Now you can continue editing the content in the Description field.

### Browsers

Chrome

### Additional context (Is this in dev or production?)

Dev and Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by deepakrudrapaul**
## Description

This PR updates the behaviour of the Title field so that it conditionally hides the Description field only when the Description field has zero content.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #1354 

## Mobile & Desktop Screenshots/Recordings

Before :
[Screencast from 15-07-23 03:08:39 PM IST.webm](https://github.com/open-sauced/insights/assets/25549935/040a5d88-c562-4cd0-98d4-82068096232e)

After :
[Screencast from 15-07-23 03:09:35 PM IST.webm](https://github.com/open-sauced/insights/assets/25549935/da56d19d-8f3b-4b37-ae45-677d6ab976b8)

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [x] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?
:smiley:

### CODE REVIEW

**Comment by jpmcb** [comment]
I also ran into this today and suggested maybe a more explicit "Close" button: https://github.com/open-sauced/insights/issues/1363

But it'd be worth getting some insight from @isabensusan or @bdougie on what approach we want to take with this specific UI / UX

**Review by bdougie — APPROVED** [review]

**Comment by bdougie** [comment]
needs a `npm run format` locally @deepakrudrapaul

**Comment by bdougie** [comment]
I think a close button would help a lot here, but can be scoped in a separate PR. This PR handles the weirdness where the input is closed when you select the title, which is not ideal UX.

There some other new UI changes coming, which will either blocked this PR or require it to merge in the next 24hrs so it is not blocking. If the build is fixed prior, then we can move forward, if not, we might need to wait until https://github.com/open-sauced/insights/pull/1381 so it can be rebased here.

**Comment by deepakrudrapaul** [comment]
Thank you for your suggestion. I have run "npm run format" and pushed the changes in a single commit, we are ready to move forward.

**Review by OgDev-01 — APPROVED** [review]
LG 🍕

**Pull request merged**
