### PR TITLE
fix: fixed bug on chatbot button overlay

### LINKED ISSUE #1416: Bug: overlay of chatbot button on links
### Describe the bug

The opensauced chat modal button is displaying over some links which makes it unable for the users to click and see on mobile view 
Screenshot_20230723-215659

### Steps to reproduce

1. Go to opensauced.pizza
2. Click on get started after authentication
3. Scroll down see chatbot button

### Browsers

Chrome

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by OpherM**
## Description
fixed bug on chatbot button overlay: The chatbot button overlays on the footer links which has now been fixed.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #1416  

## Mobile & Desktop Screenshots/Recordings
Screenshot (464)

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Review by OgDev-01 — APPROVED** [review]
Welcome to the commnunity @OpherM 🍕

**Review by NsdHSO — APPROVED** [review]
LGTM

**Comment by dev-phantom** [comment]
Nice 😊

LGTM🚀

**Review by brandonroberts — APPROVED** [review]

**Comment by OpherM** [comment]
> Welcome to the community @OpherM 🍕

Thanks for having me

**Pull request merged**
