### PR TITLE
feat: adds loading skeleton to page

### PR DESCRIPTION
**Pull request by payn33**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
- Fixes: #787 

## Mobile & Desktop Screenshots/Recordings

https://user-images.githubusercontent.com/66219025/216761198-9df97d7e-a32d-4747-af9e-42ab64898dc4.mp4

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Review by 0-vortex — APPROVED** [review]
LGTM! 👍 

Needs updating with beta and can get merged! 🍕

**Review by OgDev-01 — APPROVED** [review]
Awesome!!! 🍕 🍕 ... resolve merge conflict and this is ready to merge 👍

**Comment by bdougie** [comment]
@payn33 are you able to manage the merge conflicts?

**Comment by payn33** [comment]
> @payn33 are you able to manage the merge conflicts?

just got it resolved, thanks.

**Comment by bdougie** [comment]
@payn33 would be able to create a highlight about your work on this fix?

https://opensauced.pizza/blog/social-coding-is-back

**Comment by payn33** [comment]
> @payn33 would be able to create a highlight about your work on this fix?
> 
> https://opensauced.pizza/blog/social-coding-is-back

hello @bdougie  I keep getting an error when I try to view my profile

https://user-images.githubusercontent.com/66219025/221282121-d03face7-fb1e-4248-b6a2-b71d12f875a0.mp4

did a bit of debugging and found that the data structure for my contributor data used in the `useTopicContributorCommits` hook is different from what is expected(no idea why), hence the error.
image
the picture above is the contributor data returned for your profile(above) containing nested data and meta object, and mine (below)  an array
usecontributorcommithook
a snippet from the `usecontributorcommithook` that expects a nested data object

**Comment by bdougie** [comment]
Opened a new issue for this

**Pull request merged**
