### PR TITLE
fix: check user follow after opening highlight menu

### LINKED ISSUE #1139: Bug: feed is retrying requests indefinitely
### Describe the bug

The [feed](https://insights.opensauced.pizza/feed) page is checking whether the logged-in user is following other members - because this returns 404 when that happens, the default behaviour swr implies is to retry fetching the resource. 

That leads to a permanent API rate depletion and potentially spam, depending on how many feed tabs are left open.

Screenshot 2023-05-03 at 12 32 51

### Steps to reproduce

1. Don't follow anyone
1. Go to https://insights.opensauced.pizza/feed
1. Check console/wait

### Affected services

insights.opensauced.pizza

### Platforms

_No response_

### Browsers

_No response_

### Environment

Production, Development, Testing

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by a0m0rajab**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [x] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [x] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

Turning the following check into a functional component to call it only when it's needed instead of calling the usefollowuser always. 
fixes #1139  

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [x] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by brandonroberts** [comment]
Thanks @a0m0rajab. This was resolved via https://github.com/open-sauced/insights/pull/1164

**Comment by a0m0rajab** [comment]
@brandonroberts would it be okay to review this with the new issue opened?

**Comment by a0m0rajab** [comment]
Fixes: #1202

**Comment by brandonroberts** [comment]
@a0m0rajab Ok, check the build error so the preview can be deployed. Thanks

**Comment by takanome-dev** [comment]
@a0m0rajab there is a lint error that's failing the build (missing semicolon in `contributor-highlight-card.tsx`).
Run: `npm run format` and then `npm run build` just to make sure the build will pass and then push the changes :+1:

**Comment by a0m0rajab** [comment]
@takanome-dev thank you for the help, fixed 👍

**Pull request merged**
