### PR TITLE
fix: hide unnecessary scrollbar in profilepage

### LINKED ISSUE #1325: Bug: unnecessary scroll
### Describe the bug

There is an unnecessary scroll in the large screens on the contributor's page. 

image

### Steps to reproduce

1. go to the contributor page: https://insights.opensauced.pizza/user/a0m0rajab/contributions
2. Check the tabs area. You can see the scroll. 

Suggested solution: 

You can add `overflow:hidden` in the CSS. 

### Browsers

_No response_

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by Lucif3r-in**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
Fixes #1325 

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by a0m0rajab** [comment]
LGTM, thank you for the PR.

**Review by NsdHSO — APPROVED** [review]
LGTM

**Review by a0m0rajab — APPROVED** [review]

**Comment by brandonroberts** [comment]
Thanks @Lucif3r-in will you add a screenshot of what the change looks like in the UI for a quicker review? Thanks

**Comment by OgDev-01** [comment]
Hey @Lucif3r-in, will you include a before/after screenshot for a better review?

**Comment by Lucif3r-in** [comment]
Before
image

After
image

@brandonroberts @OgDev-01

**Review by OgDev-01 — APPROVED** [review]
LGTM 🍕

**Review by brandonroberts — APPROVED** [review]

**Pull request merged**
