### PR TITLE
feat: add dark mode

### LINKED ISSUE #56: [Front-End] Implement Dark Mode
Currently Tailwind requires us to add dark mode colors within the component. I think that makes it too unreadable and just a pain to maintain.

The way I set up the colors is:

```js
colors: {
  light: {
    "slate": {
      "1": "hsl(206, 30.0%, 98.8%)",
      ...
      "12": "hsl(206, 24.0%, 9.0%)"
    },
    "slate-a": {
      "1": "hsla(210, 92.6%, 26.5%, 0.016)",
      ...
      "12": "hsla(202, 97.0%, 2.4%, 0.934)"
    }
  },
  dark: {
    "slate": {
      "1": "hsl(200, 7.0%, 8.8%)",
      ...
      "12": "hsl(210, 6.0%, 93.0%)"
    }
  }
}
```

There should be a way for us to use these color steps as CSS Variables, so when the theme changes, only the values in the CSS Variable change, not the classes in the components.

You only declare `slate-1` once in the component, then the theme handles whether the color will be from the light or dark theme. 

I'm opening a new issue, because this is not something we need to resolve in this PR, nor is it something urgent.

_Originally posted by @pixelsbyeryc in https://github.com/open-sauced/insights/issues/55#issuecomment-1182607242_

### PR DESCRIPTION
**Pull request by takanome-dev**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [x] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
This PR adds dark mode to the platform

## Related Tickets & Documents

Fixes #56 
## Mobile & Desktop Screenshots/Recordings

Just the beginning...

dash-1

dash-2

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by bdougie** [comment]
Thanks for opening this @takanome-dev.

We haven't had bandwidth to explore dark mode in this app, but there was some work to make this approachable. 

https://github.com/open-sauced/insights/blob/beta/tailwind.config.js#L121

**Comment by takanome-dev** [comment]
> Looks like you are using that, but it doesn't cover all edge cases. We will need to document what is not covered to start cleaning this up.

Sure :+1:

**Comment by adiati98** [comment]
Hi,
Is this issue still open for contribution? If so, may I try to work on this?
Thanks! 😊

**Comment by jpmcb** [comment]
Hi @adiati98 - let's move the conversation to #56 where there looks to be some talk of implementation details and you can assign yourself 👍🏼

**Pull request closed without merging**
