### PR TITLE
feat: added new topics to the list

### LINKED ISSUE #1355: Feature: Add new topics to the list
### Type of feature

🍕 Feature

### Current behavior

Vue was requested as well as Kubernetes

https://github.com/orgs/open-sauced/discussions/11

## Add to the topics list
Screen Shot 2023-07-14 at 7 34 01 AM

## Add to the interests list
Screen Shot 2023-07-14 at 7 34 08 AM

https://github.com/open-sauced/insights/blob/86824c217733f322b931f7f33d25b70600049737/components/atoms/LanguagePill/LanguagePill.tsx#L19

### Additional context

Previous PR https://github.com/open-sauced/insights/pull/877

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by aryanas159**
## Description

adds vue and kubernetes options in the topics list as well as interests

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

fixes #1355 

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by bdougie** [comment]
Please fill out the issue template @aryanas159

**Comment by aryanas159** [comment]
@bdougie What should I put for vue and kubernetes here 

react: ["Skyscanner/backpack"],
  javascript: ["EddieHubCommunity/LinkFree"],
  python: ["randovania/randovania"],
  ml: ["mindsdb/mindsdb"],
  ai: ["LAION-AI/Open-Assistant"],
  rust: ["swc-project/swc"],
  ruby: ["rubocop/rubocop"],
  c: ["systemd/systemd"],
  cpp: ["redpanda-data/redpanda"],
  csharp: ["ScottPlot/ScottPlot"],
  php: ["laravel/framework"],
  java: ["thingsboard/thingsboard"],
  typescript: ["sequelize/sequelize"],
  golang: ["cli/cli"],

**Comment by brandonroberts** [comment]
> @bdougie What should I put for vue and kubernetes here
> 
> react: ["Skyscanner/backpack"], javascript: ["EddieHubCommunity/LinkFree"], python: ["randovania/randovania"], ml: ["mindsdb/mindsdb"], ai: ["LAION-AI/Open-Assistant"], rust: ["swc-project/swc"], ruby: ["rubocop/rubocop"], c: ["systemd/systemd"], cpp: ["redpanda-data/redpanda"], csharp: ["ScottPlot/ScottPlot"], php: ["laravel/framework"], java: ["thingsboard/thingsboard"], typescript: ["sequelize/sequelize"], golang: ["cli/cli"],

You don't have to put anything here. Recommendations are provided dynamically through the API. This file can be deleted.

**Review by bdougie — APPROVED** [review]
It works for me.

**Comment by bdougie** [comment]
> note

fixes #1355 and not fixes issues #1355

**Review by brandonroberts — APPROVED** [review]

**Pull request merged**
