### PR TITLE
feat: add Explore to nav

### LINKED ISSUE #661: feature: Add an "Explore" link in nav
### Type of feature

Select the type of feature request, the lowercase should also be the PR prefix.

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

### Current behavior

Screen Shot 2022-12-14 at 1 40 25 PM

### Suggested solution

Link to "https://insights.opensauced.pizza/javascript/dashboard/filter/recent"

### Code of Conduct

By submitting this issue, you agree to follow our [Code of Conduct](https://docs.opensauced.pizza/contributing/code-of-conduct/).

- [x] I agree to follow this project's Code of Conduct

### Contributing Docs

If you plan on contributing code please read - [Contribution Guide](https://docs.opensauced.pizza/contributing/introduction-to-contributing/)

- [x]  I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by Deadreyo**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

Adds an Explore button in top navigation bar that links to `/javascript/dashboard/filter/recent`. This makes it possible to navigate between different sections of the project.

Note:
- A new issue should be opened that would make the 'Insight Hub' link red if we are in hub section, or make 'Explore' link red if we are in explore section.

## Related Tickets & Documents

fixes #661 
## Mobile & Desktop Screenshots/Recordings
image

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by brandonroberts** [comment]
If the deploy preview failed, check for lint errors by running

```sh
npm run format
```

**Comment by Deadreyo** [comment]
solved

**Comment by brandonroberts** [comment]
@bdougie  The `Explore` link be shown even if they aren't logged in/onboarded? So they can get back to it if they entered a filter on one of the pages

**Review by 0-vortex — APPROVED** [review]
LGTM! 👍 

If going the logged in/out route, would argue the "explore" link should turn into "login" when user is not logged in for visual cohesion 🍕

**Review by bdougie — APPROVED** [review]

**Comment by Deadreyo** [comment]
> @bdougie The `Explore` link be shown even if they aren't logged in/onboarded? So they can get back to it if they entered a filter on one of the pages

I think that should be made into another issue.




> If going the logged in/out route, would argue the "explore" link should turn into "login" when user is not logged in for visual cohesion 🍕

I'd say have both "Explore" link to identify the user of what section he is in, and "Login" beside it

**Pull request merged**
