### PR TITLE
fix: update local time option from user settings

### LINKED ISSUE #946: Bug: Localtime settings doesn't do anything
### Describe the bug

Screen Shot 2023-03-03 at 3 37 54 PM

reported by @styfle

### Steps to reproduce

Users expect time to be removed from the profile. We should do that :)

### Affected services

insights.opensauced.pizza

### Platforms

_No response_

### Browsers

_No response_

### Environment

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by OgDev-01**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
This PR updates `display local time` check option in user's settings to reflect previously saved value and also hide timezone ui when this option is false

## Related Tickets & Documents
Fixes #946 

## Mobile & Desktop Screenshots/Recordings
image

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Review by bdougie — APPROVED** [review]

**Comment by brandonroberts** [comment]
@OgDev-01 @bdougie we are currently using this setting here 

https://github.com/open-sauced/insights/blob/beta/components/molecules/ContributorProfileInfo/contributor-profile-info.tsx#L76

That needs to be updated also if we're no longer using this setting

**Comment by bdougie** [comment]
> @OgDev-01 @bdougie we are currently using this setting here

If the setting is being used in the UI, it doesn't seem to be not working as intended. Can you confirm @OgDev-01. This was the report from Steven, we may have jumped to a conclusion to remove the feature rather than fix it.

image

**Comment by OgDev-01** [comment]
I just confirmed that the value is being used in the user profile. Just a minor issue with the checkbox because its default value is not populated from the user's data but a local state variable. So when a user updates their profile to show the date and reloads the page, the checkbox remains unchecked even if the settings have been updated

image

The `displayLocalTime` value is derived from a local `useState` variable and i think that's what needs fixing

**Review by bdougie — CHANGES_REQUESTED** [review]
We incorrectly interpreted this request from the user. We should remove timezone from the public profile in addition to local time when this is selected.

Leave the setting available.

**Comment by OgDev-01** [comment]
Option added back and now reflects users previously saved value by defauilt
image

**Review by brandonroberts — APPROVED** [review]
LGTM

**Review by 0-vortex — APPROVED** [review]
Thought this switch in the user settings would change the display from "bdougie time is 09:00" to "-10 hrs behind", otherwise LGTM! 👍

**Review by Deadreyo — APPROVED** [review]

**Pull request merged**
