### PR TITLE
feat: remove default user bio

### LINKED ISSUE #922: Bug: Default profile bio should not show.
### Describe the bug

I find it weird we got this far with user having a passion for music and coding. 

Screen Shot 2023-02-28 at 9 35 42 AM

### Steps to reproduce

View this profile. https://deploy-preview-920--oss-insights.netlify.app/user/meeroslav

If they do not have a profile we should the below bio instead of this generic bio.

```
[user] has connect their GitHub, but has not added a bio.
``` 

The best solution would be adding the bio from GitHub as the default.

Screen Shot 2023-02-28 at 9 38 03 AM

### Affected services

insights.opensauced.pizza

### Platforms

_No response_

### Browsers

_No response_

### Environment

_No response_

### Additional context

The default timezone is also UTC+1 but it should not show if it is not submitted.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by shamimbinnur**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
This PR replaces the user's `default bio` with the message `[user] has connected their GitHub but has not added a bio.` I made the message a little pale.

## Related Tickets & Documents
Fixes #922 

## Mobile & Desktop Screenshots/Recordings

Screenshot 2023-03-01 at 9 54 09 AM

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Review by bdougie — APPROVED** [review]
Looks good.

**Review by OgDev-01 — APPROVED** [review]

**Review by 0-vortex — CHANGES_REQUESTED** [review]
LGTM, but please change the string math to text literals / normal string expansion:

```
description: `${user?.bio || `${profile?.githubName} has connected their GitHub but has not added a bio.`)}`,
```

**Comment by shamimbinnur** [comment]
> LGTM, but please change the string math to text literals / normal string expansion:
> 
> ```
> description: `${user?.bio || `${profile?.githubName} has connected their GitHub but has not added a bio.`)}`,
> ```

@0-vortex loved this solution!

**Comment by brandonroberts** [comment]
@shamimbinnur there's another one here that's displayed on the user profile that needs to be updated

https://github.com/open-sauced/insights/blob/beta/components/molecules/ContributorProfileInfo/contributor-profile-info.tsx#L72

**Comment by shamimbinnur** [comment]
@brandonroberts But, I have updated the other file as well.

https://github.com/shamimbinnur/insights/blob/3bd9335b94f9b38c569cda620eea13abd35d0590/components/molecules/ContributorProfileInfo/contributor-profile-info.tsx#L73

**Comment by brandonroberts** [comment]
@shamimbinnur ok cool, must have glanced over it

**Review by brandonroberts — APPROVED** [review]

**Pull request merged**
