### PR TITLE
fix: fixed margin issues on layout

### LINKED ISSUE #1526: Bug: margin removed from the titles!
### Describe the bug

If you open insight page on small screens the titles will not be shown: 

image

On large screens the titles will be close to the header:

image

### Steps to reproduce

N/A

### Browsers

_No response_

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### LINKED ISSUE #1531: Bug: no margin top in the explore, highlight and insight page
### Describe the bug

The header on the insight page is currently covering the content on the the insight page, the explore tab  and the highlight I guess this was because the header was fixed to the top 
Here's a screenshot 
Screenshot_20230809-052136

### Steps to reproduce

1. On mobile visit https://insights.opensauced.pizza/start
2. Get authenticated 
3. See error 

### Browsers

Chrome

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by dev-phantom**
## Description
This PR fixes margin top issues in the explore, highlight and insight page
this error was from my previous PR after setting the topNav header to fix 

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [x] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #1531 and Fixes #1526 
## Mobile & Desktop Screenshots/Recordings
image

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## Note to reviewers
Kindly take your time to review this and let me know if this issue still persist
Thanks

### CODE REVIEW

**Review by brandonroberts — APPROVED** [review]

**Comment by brandonroberts** [comment]
@dev-phantom will you add desktop before/after screenshots also

**Review by bdougie — APPROVED** [review]

**Comment by dev-phantom** [comment]
This issue was not still fixed after deployment kindly revert to the previous commit before #1506

I'm very sorry for causing these issues this was caused from setting the topNav header to a fixed position

**Comment by dev-phantom** [comment]
Although I also wonder why it works fine locally and on netlify deploy preview

But doesn't work after deployment 🤔

**Comment by dev-phantom** [comment]
> @dev-phantom I don't think this is deployed to prod yet but it's on beta. Check [beta.insights.opensauced.pizza](https://beta.insights.opensauced.pizza)

Oh 😳

Thanks for giving me hope 😊

**Pull request merged**
