### PR TITLE
feat: Responsive nav

### PR DESCRIPTION
**Pull request by nworiekingslee**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
I just added tailwind classnames to make the top-nav more responsive using the image shared on the issue (#866) as a reference

## Related Tickets & Documents

#866

## Mobile & Desktop Screenshots/Recordings
Screenshot 2023-03-19 at 00 18 51
Screenshot 2023-03-19 at 00 20 31

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by NsdHSO** [comment]
LGTM

**Comment by brandonroberts** [comment]
Thanks @nworiekingslee, should the avatar still be aligned at the top?

**Review by OgDev-01 — APPROVED** [review]
Align user avatar to top and we're good on this 🍕

**Comment by nworiekingslee** [comment]
Hello @brandonroberts, I have made the fix based on your recommendation

Screenshot 2023-03-21 at 00 43 26
Screenshot 2023-03-21 at 00 43 46

**Comment by nworiekingslee** [comment]
I went ahead to resolve the merge conflict, I hope it's fine to do that.

**Review by 0-vortex — APPROVED** [review]
LGTM! 👍

**Review by brandonroberts — APPROVED** [review]

**Pull request merged**
