### PR TITLE
feat: add support for goto page functionality

### LINKED ISSUE #675: Feature: Jump to pagination
### Type of feature

🍕 Feature

### Current behavior

Pagination currently requires the user to jump multiple pages to get to where they need. 

Screen Shot 2022-12-16 at 3 42 25 PM

### Suggested solution

User should be able to manually enter the page. 

https://github.com/open-sauced/insights/blob/beta/lib/hooks/useRepositoriesList.ts#L21

  
Screen Shot 2022-12-16 at 3 15 41 PM

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by SunGoldTech**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
This PR includes the support for goto page functionality on the repositories and contributors page

### Notes:
The Ui was worked on here https://github.com/open-sauced/insights/pull/357 and the implementation was done here https://github.com/open-sauced/insights/pull/405

## Related Tickets & Documents
Fixes #675 

## Mobile & Desktop Screenshots/Recordings
image

image

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [x] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by Deadreyo** [comment]
bug: using arrows to change pages no longer updates the page counter if the user put a number in it. Recorded a gif: 
KIpcBISPVN

**Comment by SunGoldTech** [comment]
> bug: using arrows to change pages no longer updates the page counter if the user put a number in it. Recorded a gif: KIpcBISPVN [ KIpcBISPVN ](https://user-images.githubusercontent.com/52013393/209096628-8e426a0a-8bd8-4f01-ab6b-d33c81509b42.gif) [ ](https://user-images.githubusercontent.com/52013393/209096628-8e426a0a-8bd8-4f01-ab6b-d33c81509b42.gif)

Thanks for noticing this 👍

**Comment by Deadreyo** [comment]
bug: it's allowed to try to go above the pages limit present. 

In this example: there are 169 pages but I was allowed to try to visit page 190
image

**Comment by TAKANOME-DEV** [comment]
I'm getting the same repos no matter what page I'm on.
When inspecting the network tab, each request retrieves new data, but the UI does not update :thinking:

**Comment by Deadreyo** [comment]
> I'm getting the same repos no matter what page I'm on. When inspecting the network tab, each request retrieves new data, but the UI does not update 🤔

It will work if you click on one of the table header cells to re-order the items. This is a bug but not related ot this PR

**Comment by TAKANOME-DEV** [comment]
>> I'm getting the same repos no matter what page I'm on. When inspecting the network tab, each request retrieves new data, but the UI does not update :thinking:
>
> It will work if you click on one of the table header cells to re-order the items. This is a bug but not related ot this PR
>
Thanks for the clarification :+1:

**Comment by SunGoldTech** [comment]
Hey @bdougie, was wondering if we could introduce system notification here as we have in hot https://github.com/open-sauced/hot/pull/285, to enable user's get feedback when they input a number above the total page count?

**Review by bdougie — CHANGES_REQUESTED** [review]
Can we add the page number to the URL? 

`https://deploy-preview-708--oss-insights.netlify.app/javascript/repositories/filter/top-100-repos?page=4`

This is not present on main, and would make it easier for the user to navigate

**Comment by bdougie** [comment]
> would suggest we create a follow-up issue for this.

Please do open up the issue.

**Review by bdougie — APPROVED** [review]

**Review by brandonroberts — APPROVED** [review]

**Comment by 0-vortex** [comment]
Didn't manage to get to this PR in time but we are doing [keys](https://reactjs.org/docs/lists-and-keys.html) really poorly; even tho this is not an isolated issue, this PR introduces 2 instances of the index key, a minor follow-up could be really fast! 🍕

**Pull request merged**
