### PR TITLE
feat: create reuseable error component

### LINKED ISSUE #781: Feature: Error messages
### Type of feature

🍕 Feature

### Current behavior

When a user submits a form and an error occurs. We do not have a consistent error message style. 

Screen Shot 2023-01-14 at 9 20 52 AM

Screenshot above is from  https://github.com/open-sauced/insights/pull/725

Screen Shot 2023-01-14 at 9 24 02 AM

The above is from the new [user settings page](https://www.figma.com/file/OpVX6WT7dmWqnwRuEvADMF/OpenSauced-%E2%80%94-Insights-(insights.opensauced.pizza)?node-id=5619%3A5814&t=455oLoVYAx3UF7mV-0). 

### Suggested solution

We need a consistent component for the entire app. My suggestion is using either red text or red underlined text. 

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by shamimbinnur**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

#### This PR:
Adds reusable error [component](https://github.com/open-sauced/insights/blob/7b6d7cb84fc9fd786beeee69052ccf957d157840/components/atoms/Error/Error.tsx).
-It takes errorMessage as a string for its optional parameter. If the errorMessage is not passed it will show the default error message "Something went wrong".

-It takes the optional fullWide as a boolean parameter. The default value is `false`. We have to pass the value true if we want 
 to make it full-wide.

I used this component for repo look up error message.

## Related Tickets & Documents
Fixes #781 #700 

## Mobile & Desktop Screenshots/Recordings
Retrieving error
Screenshot 2023-03-06 at 5 59 07 PM

Not indexed.
Screenshot 2023-03-06 at 5 58 47 PM

Invalid repo error.
Screenshot 2023-03-06 at 5 58 27 PM

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by bdougie** [comment]
When a repo is not being indexed, we still want the user to go to the discussion for now.

**Comment by shamimbinnur** [comment]
> When a repo is not being indexed, we still want the user to go to the discussion for now. Your updated error message does not provide that context.
> 
> 
image

@bdougie 
We still have the component to visit the discussion page if the repo is not indexed.
Did you mean something else?
Screenshot 2023-03-06 at 7 22 58 PM

**Comment by brandonroberts** [comment]
@shamimbinnur this needs at least one story for this to the design system also.

Some examples are in the `atoms` folder https://github.com/open-sauced/insights/tree/beta/stories/atoms

**Comment by shamimbinnur** [comment]
@brandonroberts added stories!

**Review by brandonroberts — APPROVED** [review]
LGTM

**Review by bdougie — APPROVED** [review]

**Review by OgDev-01 — APPROVED** [review]

**Pull request merged**
