### PR TITLE
fix: user interest logo error 

### LINKED ISSUE #1469: Bug: AI and Machine Learning logo is not displaying in current interest
### Describe the bug

In the user profile the AI and Machine Learning logo is not displaying in current interest section
you can check it out here 
https://insights.opensauced.pizza/user/dev-phantom/highlights

here is a screenshot:
Screenshot (10)

### Steps to reproduce

1. go to https://insights.opensauced.pizza/
2. click on the github profile picure dropdown 
3. navigate to your account profile 
4. scroll down to current interest
5. see error

### Browsers

Chrome

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by anubhav1206**
## Description
fixed #1469 

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by OgDev-01** [comment]
Hey @anubhav1206, Thanks for this quick fix... Can you go through  [this](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) quickly and link the related issue to this PR

**Comment by anubhav1206** [comment]
> Hey @anubhav1206, Thanks for this quick fix... Can you go through [this](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) quickly and link the related issue to this PR

sure

**Comment by anubhav1206** [comment]
> Member
done

**Comment by anubhav1206** [comment]
> Hey @anubhav1206, Thanks for this quick fix... Can you go through [this](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) quickly and link the related issue to this PR

done

**Review by OgDev-01 — APPROVED** [review]
🍕

**Comment by OgDev-01** [comment]
Just a side note: It's good practice to add a brief description and screenshots/records(if changes are visually seen) of what was done in the PR before and after. This helps for future references and a quicker review 🍕

**Review by brandonroberts — APPROVED** [review]

**Pull request merged**
