### PR TITLE
fix: thumbnail topic images

### LINKED ISSUE #1007: Bug: Official logos are not being leverage.
### Describe the bug

Screen Shot 2023-03-14 at 3 30 52 PM

This PR https://github.com/open-sauced/insights/pull/995 deleted the work ins PR https://github.com/open-sauced/insights/pull/966

### Steps to reproduce

image

Topic thumbnails should be what appears above. The interest emojis should be different. 

### Affected services

insights.opensauced.pizza

### Platforms

_No response_

### Browsers

_No response_

### Environment

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by OgDev-01**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
This PR fixes the wrong thumbnail issue on insights page

## Related Tickets & Documents
Closes #1007 

## Mobile & Desktop Screenshots/Recordings
image

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Review by 0-vortex — APPROVED** [review]
Fixes the problem but have to ask, if all our icons are SVG, why do we have them twice? We can just use the "big" (HD) resolution for both and make the thumbnail a smaller size 🤷 🍕

**Comment by OgDev-01** [comment]
> Fixes the problem but have to ask, if all our icons are SVG, why do we have them twice? We can just use the "big" (HD) resolution for both and make the thumbnail a smaller size 🤷 🍕

The names are identical, but the icons are different 👌. So if we have javascript in `image/icons/interests` and `img/topic-thumbnails` both are totally different images

**Review by bdougie — CHANGES_REQUESTED** [review]
Add Rust and Go

**Comment by getaheaddev** [comment]
[[Figma File](https://www.figma.com/file/OpVX6WT7dmWqnwRuEvADMF/OpenSauced-%E2%80%94-Insights-(insights.opensauced.pizza)?node-id=5953%3A6991&t=NT6Gu8AalxdvVHrC-1)]

[[Video: Exporting files out of Figma](https://www.loom.com/share/0edeaa7d62c2403f82a4129a9ace7989)]

**Comment by OgDev-01** [comment]
Thanks @getaheaddev

**Comment by OgDev-01** [comment]
> Add Rust and Go

Is this the one for rust? 
image

**Review by bdougie — APPROVED** [review]

**Comment by bdougie** [comment]
> @OgDev-01
> 
> [[Figma File](https://www.figma.com/file/OpVX6WT7dmWqnwRuEvADMF/OpenSauced-%E2%80%94-Insights-(insights.opensauced.pizza)?node-id=5953%3A6991&t=NT6Gu8AalxdvVHrC-1)]
> 
> [[Video: Exporting files out of Figma](https://www.loom.com/share/0edeaa7d62c2403f82a4129a9ace7989)]
> 
> AI Avatar ML Avatar

Still waiting on this. But approved

**Review by bdougie — APPROVED** [review]

**Pull request merged**
