### PR TITLE
feat: replace supabase checkbox with radix ui

### LINKED ISSUE #902: refactor: replace Supabase `Checkbox` with Radix
This issue is to replace our current Checkbox from Supabase ui to Radix

https://www.radix-ui.com/docs/primitives/components/checkbox

Discussed here https://github.com/open-sauced/insights/issues/338

### PR DESCRIPTION
**Pull request by takanome-dev**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [x] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

This PR replaces the Supabase checkbox with the Radix UI checkbox.
Note: I tried making the check icon bigger/bolder but it didn't work, so doesn't look the same as the Supabase one.
## Related Tickets & Documents

Fixes #902 
## Mobile & Desktop Screenshots/Recordings

checkbox-1
checkbox-2

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by Deadreyo** [comment]
I don't like the focus effect after clicking, ex: 
image

@bdougie what are your thoughts on this?

**Review by Deadreyo — APPROVED** [review]
Other than the above comment on focus effect, LGTM! Good job!

**Review by OgDev-01 — APPROVED** [review]
LGTM... Except the focus ring when the check is unchecked 🍕

**Review by bdougie — CHANGES_REQUESTED** [review]
1. Remove the focus ring
2. Lessen the raidus of the checkbox (this implementation makes it look a circle and not a box)

This is what is in production:
Screen Shot 2023-05-01 at 8 57 52 AM

**Comment by takanome-dev** [comment]
Note that I have used an arbitrary value for the border radius because it looks more than what is in prod (rounded-md is 6px and is what I used initially)
| rounded-[4px] | rounded-sm |
| ------ | ------ |
|checkbox-new-1 | checkbox-new-3 |
| checkbox-new-2 | checkbox-new-4 |

**Review by bdougie — APPROVED** [review]

**Review by 0-vortex — APPROVED** [review]
LGTM! 👍

**Review by brandonroberts — APPROVED** [review]

**Pull request merged**
