### PR TITLE
feat: highlight date selection 

### LINKED ISSUE #1032: Feature: Allow a user to select the date of a highlight
### Type of feature

🍕 Feature

### Current behavior

Currently if you add a new highlight on your insights homepage, you can add a title and a body. There is a date, but it is always the current date.

For example, here are past contributions I added retroactively but they appear to have been done on March 20th, 2023.

CleanShot 2023-03-20 at 22 33 12

### Suggested solution

Default to the current date when someone adds a highlight, but allow them to pick a date if they want. For example, on Polywork you can do this when adding a portfolio update.

CleanShot 2023-03-20 at 22 36 58

In terms of date pickers, a native browser one could be used, but there are React based ones out there too if that is something we want to consider. A quick Google pops this post from Log Rocket about picking a date picker, https://blog.logrocket.com/top-react-date-pickers-for-2021/

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by OgDev-01**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
This PR

- Adds the `shipped_date` field to highlight 
- Adds a new calendar component to the design system
- Adds a popover component from [radix](https://www.radix-ui.com/docs/primitives/components/popover)
- refactor the highlight input form toggle state to use popover

## Related Tickets & Documents

Closes #1032 

## Mobile & Desktop Screenshots/Recordings

image

image

image

image

image

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [x] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Review by bdougie — CHANGES_REQUESTED** [review]
Can you love the date icon to the bottom left?

**Comment by getaheaddev** [comment]
@bdougie @OgDev-01  I don't see a lot of context on this. Are we scheduling highlights with this?

**Comment by bdougie** [comment]
> @bdougie @OgDev-01  I don't see a lot of context on this. Are we scheduling highlights with this?

Can you link the issue @OgDev-01

**Comment by bdougie** [comment]
> @bdougie @OgDev-01  I don't see a lot of context on this. Are we scheduling highlights with this?

Can you link the issue @OgDev-01

**Comment by OgDev-01** [comment]
Here is how it looks when a date is selected
image

cc: @bdougie @getaheaddev

**Comment by brandonroberts** [comment]
The `shipped_at` field is available for creating/updating user highlights. It should be a `Date` type

**Comment by brandonroberts** [comment]
@OgDev-01 I don't see the date picker when editing a highlight

image

**Comment by OgDev-01** [comment]
> @OgDev-01 I don't see the date picker when editing a highlight

Interesting how i forgot to add that 😄 .. Thanks for catching this 👍

**Comment by getaheaddev** [comment]
We need to hold the breaks for this so I can add some design to this. The icon should be on the bottom left below the text input. for both the creation of the highlight and editing the highlight after its been made

**Comment by OgDev-01** [comment]
The `created_at` field on highlight has been updated to the new `shipped_at`
image

Am i right on this?
cc @bdougie

**Comment by OgDev-01** [comment]
> Not entirely. We are adding a shipped_at field for the originally date the content was created on GitHub.
> 
> The created_at date is still need to sort highlights and the date the highlight was created on opensauced.

Ok... Initially thought we would want to display the originally created date to users... It would be nice if they see that information from the UI as well though

**Comment by bdougie** [comment]
Today that date is in the GitHub social card. Until we expand beyond just PRs we can collect data and user feedback on what we do next.

**Review by bdougie — APPROVED** [review]
This will need design help. I don't think we need to put the date in the highlight, but instead `X time ago`. But for now, let's ship it and see where if it gets used.

**Review by brandonroberts — APPROVED** [review]
LGTM

**Pull request merged**
