### PR TITLE
fix: update avatar style to remain aligned with the input field

### LINKED ISSUE #1035: Bug: user image is not aligned with Create Highlight input box
### Describe the bug

image

Misalignment of the image with the input box on `/user/{name}/highlight`

### Steps to reproduce

`/user/{name}/highlight`

Suggested solution: try stretching the image to fit, and try just aligning center, and choose the best looking solution.

### Affected services

insights.opensauced.pizza

### Platforms

_No response_

### Browsers

_No response_

### Environment

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by Anush008**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
This PR intends to fix the avatar misalignment in https://insights.opensauced.pizza/feed.

## Related Tickets & Documents
Closes #1035. 

## Mobile & Desktop Screenshots/Recordings
Before the patch:
before

After the patch:
after

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Review by 0-vortex — APPROVED** [review]
LGTM, what about the `lg` size?

**Comment by Anush008** [comment]
> LGTM, what about the `lg` size?

Do you mean why the `lg` size? That was set before I started, intending it to be hidden for smaller devices. However, now that you've mentioned it, I think it wouldn't hurt to make it visible for smaller screens too.

**Comment by 0-vortex** [comment]
> > LGTM, what about the `lg` size?
> 
> Do you mean why the `lg` size? That was set before I started, intending it to be hidden for smaller devices. However, now that you've mentioned it, I think it wouldn't hurt to make it visible for smaller screens too.

Good reasoning but that is not what `lg-inline` does now. Tailwind aggregates from mobile first, so that class is changing the layout on `lg` screens. My question is if you accounted/tested on that particular screen size 🍕

**Comment by Anush008** [comment]
> > > LGTM, what about the `lg` size?
> > 
> > 
> > Do you mean why the `lg` size? That was set before I started, intending it to be hidden for smaller devices. However, now that you've mentioned it, I think it wouldn't hurt to make it visible for smaller screens too.
> 
> Good reasoning but that is not what `lg-inline` does now. Tailwind aggregates from mobile first, so that class is changing the layout on `lg` screens. My question is if you accounted/tested on that particular screen size 🍕

I am not quite sure if I'm getting what you mean. The breakpoint `lg` applies the layout for larger screens with viewport width 1024px or higher, correct? So, the avatar will only be visible for lg screens, since it is hidden by default for smaller screens. I've tested the changes for `lg` screen sizes after applying the patch, they look aligned as expected.

**Comment by Anush008** [comment]
To add to this, the screenshots are from an `lg` sized screen. Maybe the cropping of the image caused the confusion.

**Review by OgDev-01 — APPROVED** [review]
LGTM 🍕

**Comment by OgDev-01** [comment]
I believe we still want the avatar at the top when the inputs are open

**Comment by OgDev-01** [comment]
Like this i mean
highlight-avatar

**Comment by Anush008** [comment]
### Input not in focus:
not-focus-input

### Input in focus:
focus-input

**Pull request merged**
