### PR TITLE
feat: use repository recommendations from the API

### LINKED ISSUE #1296: Bug: Recommended Repos are undefined
### Describe the bug

I tried to run the project locally and when I tried to go to the user details page the app crashed with the following error message:

Screenshot 2023-06-24 at 12 19 14 PM

I tried to debug the issue and learned it occurred due to the user's interests string received from the backend. The string received is the following:

`",javascript,typescript"`

Due to the comma at the start of the string when we convert the interests string into an array using `array.split(",")` the first element of the array becomes `undefined` which causes the app to crash.

### Steps to reproduce

1. Clone the repository.
2. Run the project locally using `npm run dev`.
3. Authenticate the user using your GitHub account.
4. Visit your own profile from the dropdown in the top right corner.

### Browsers

Chrome

### Additional context (Is this in dev or production?)

dev

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by brandonroberts**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [x] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

- Connects user recommendations tab to selected user interests
- Refactors User Repository Recommendations into a separate component
- Fixes bug where tab switching was not reflected in the URL
- Adds a URL for recommendations to the user profile
- Also cleans up some linter checks for imports

## Related Tickets & Documents

Closes #1296 

## Mobile & Desktop Screenshots/Recordings

BEFORE:

image

AFTER:

image

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by bdougie** [comment]
Are we filtering based on stars in the data still? Freecodecamp and React seem so out of reach for even an experienced developer.

**Comment by brandonroberts** [comment]
> 

No, we're not filtering on stars. Its the active repositories that have been most recently updated that are returned. This is development data so its a bit stale

**Comment by bdougie** [comment]
Oh that makes. The dev data always throws me off. I also tried testing the api in swagger but couldn't get a dev token to test on beta.

Regardless, let's move forward with this. It is much better than our current solution. 

We will continue to tweak it after it's live.

**Review by bdougie — APPROVED** [review]
Let's move forward with it!

**Pull request merged**
