### PR TITLE
feat: implement followers highlights tab

### LINKED ISSUE #1088: Feature: Add following and home tab on highlights
### Type of feature

🍕 Feature

### Current behavior

@OgDev-01 can we add the following tab to the highlights feed.

### Suggested solution

I think this is commented our code. 

https://github.com/open-sauced/insights/blob/beta/pages/feed/index.tsx#L113-L214

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by OgDev-01**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
This PR: 

- adds the following tab to view highlights of followed users
- refactors the feeds page component to be more readable
- adds filter for followed user's highlights

## Related Tickets & Documents
Fixes #1088 

## Mobile & Desktop Screenshots/Recordings
image

image

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by bdougie** [comment]
Still need the ability to create a highlight on the following tab image

**Comment by brandonroberts** [comment]
@OgDev-01 for clarity, we should reference files, hooks, and other things here as `Following` instead of `Follower`. This feature shows highlights for people you're following, and not for your followers.

**Comment by takanome-dev** [comment]
Shouldn't we add a message if the user is not following anyone?

following-empty

**Comment by OgDev-01** [comment]
> Shouldn't we add a message if the user is not following anyone?
> 
> following-empty

You're right... I have a new component that can be leveraged to show a message if a user is not following anyone [here](https://github.com/open-sauced/insights/blob/66cc1d9196f211f35caff88ea5751661dcec1a66/components/atoms/DashedContainer/DashContainer.tsx#L7).

**Comment by bdougie** [comment]
> You're right... I have a new component that can be leveraged to show a message if a user is not following anyone [here](https://github.com/open-sauced/insights/blob/66cc1d9196f211f35caff88ea5751661dcec1a66/components/atoms/DashedContainer/DashContainer.tsx#L7).

Trust the design system. We already have the element, can you product a list with avatars, a bio and follow button

Taken from [[Figma](https://www.figma.com/file/768ifqOGWrsRN29Igkc4ip/User-Flows?type=design&node-id=205-1661&t=QwAMo7Mwjc7dP81c-0)] 
Screen Shot 2023-05-16 at 9 59 33 AM

**Comment by OgDev-01** [comment]
#1174 needs to be merged to unblock this implementation
cc: @brandonroberts 

> > You're right... I have a new component that can be leveraged to show a message if a user is not following anyone [here](https://github.com/open-sauced/insights/blob/66cc1d9196f211f35caff88ea5751661dcec1a66/components/atoms/DashedContainer/DashContainer.tsx#L7).
> 
> Trust the design system. We already have the element, can you product a list with avatars, a bio and follow button
> 
> Taken from [[Figma](https://www.figma.com/file/768ifqOGWrsRN29Igkc4ip/User-Flows?type=design&node-id=205-1661&t=QwAMo7Mwjc7dP81c-0)] Screen Shot 2023-05-16 at 9 59 33 AM

Yeah this can be accomplished in a separate issue... I added a fallback message for now

image

**Review by bdougie — APPROVED** [review]
Thanks for turning this around. The message box for no followers is perfect, we can improved it later.

**Review by brandonroberts — APPROVED** [review]

**Comment by brandonroberts** [comment]
@OgDev-01 after merge conflicts are resolved, this one is ready to merge

**Pull request merged**
