### PR TITLE
feat: replace user avatar from github with the cached one

### LINKED ISSUE #757: Feature: Update avatar caching
### Type of feature

🍕 Feature

### Current behavior

Currently, avatars shown in the chart are cached in Cloudinary, while the ones in the hover card are cached in the API. 
This can result in mismatched avatars being displayed on different pages of the site.

| avatar_1_edit | avatar_2_edit |
| --------- | --------- |

### Suggested solution

Maybe having a sort of consistent caching strategy for avatars across all pages of the site may solve this issue :thinking: 

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by TAKANOME-DEV**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

This PR replaces the user avatar from Github on the dashboard page with the cached one using Cloudinary
## Related Tickets & Documents

Fixes #757 
## Mobile & Desktop Screenshots/Recordings

pr-screen-1

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Review by OgDev-01 — APPROVED** [review]
LGTM 🍕

**Comment by OgDev-01** [comment]
Is this still in progress @TAKANOME-DEV ?

**Comment by 0-vortex** [comment]
> LGTM 🍕 

You missed the conversation about user avatars not being loaded. This is a draft for us to help solve this issue ❤️

**Comment by TAKANOME-DEV** [comment]
> Is this still in progress @TAKANOME-DEV ?

Yeah, I need help about this issue :arrow_down:  (read more -> https://github.com/open-sauced/insights/issues/757):

avatar_updated_issues

**Pull request closed without merging**
