### PR TITLE
fix:  Under mobile mode Github link under Highlights are not properly inside card if link is longer #1052

### PR DESCRIPTION
**Pull request by parmishh**
Under mobile mode Github link under Highlights are not properly inside card if link is longer #1052

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
Under mobile mode Github link under Highlights are not properly inside card if link is longer #1052

## Related Tickets & Documents
Fixes https://github.com/open-sauced/insights/issues/1052

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by parmishh** [comment]
@bdougie could you review it

**Comment by parmishh** [comment]
@OgDev-01 

Before making changes:
227738265-1bd14765-f3aa-4617-8234-f1ddc578c925


After making changes:
227738730-acabaaa2-0a90-4f11-85cb-e95c44f1c66c

**Review by 0-vortex — APPROVED** [review]
LGTM! 👍

**Review by OgDev-01 — APPROVED** [review]
LGTM 🍕 🍕

**Pull request merged**
