### PR TITLE
feat: Added a placeholder in the search input for a full repo name

### PR DESCRIPTION
**Pull request by SimranjitKaurMaan**
## What type of PR is this? (check all applicable)

- [X] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
Added a placeholder in the search input for a full repo name eg: facebook/react to facilitate the search user experience. Without the placeholder user might be confused about the search text as this search is not a free text search. Hence adding a placeholder might help to hint at a valid search text.
Fixes issue in #789 

## Mobile & Desktop Screenshots/Recordings
image

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by bdougie** [comment]
I think this is helpful, but not sure if how helpful though. Perhaps not many users are using the search feature. 

@open-sauced/triage squad thoughts?

**Comment by TAKANOME-DEV** [comment]
Having a search feature may be helpful, but it's a pain to type `repo_owner/repo_name` for me.
Being able to search for a name and get some results matching the search query would be nice.

**Comment by bdougie** [comment]
Yeah to @TAKANOME-DEV. Making search work from the GitHub api is the actual fix. Let's leave this open but use the issue to share solutions.

**Comment by brandonroberts** [comment]
I agree being able to search the GitHub API using an autocomplete field would be ideal here, but then we could get rate limited. On the API side of things we still need to search for a specific repo by full name to mitigate expensive searches through the whole dataset of repos

**Comment by 0-vortex** [comment]
> I agree being able to search the GitHub API using an autocomplete field would be ideal here, but then we could get rate limited. On the API side of things we still need to search for a specific repo by full name to mitigate expensive searches through the whole dataset of repos

Search API is generally not limited, think your approach is great! 🍕

**Comment by bdougie** [comment]
We need to rethink this. Going to have @Deadreyo and @getaheaddev work on this.

**Pull request closed without merging**
