### PR TITLE
feat: onboarding auto fetch timezone

### LINKED ISSUE #948: Feature: Determine the timezone based on the browser.
### Type of feature

🍕 Feature

### Current behavior

reported on [Twitter by JayCooperBell](https://twitter.com/JayCooperBell/status/1632036192601669634).

> Hey 
[@saucedopen](https://twitter.com/saucedopen)
, just signed up, couple pieces of feedback, you should be able to determine my timezone from my browser and auto fill, PST and PDT are the same timezone (just depends on time of year), your form field regexes are case sensitive but phones capitalize first letter.

### Suggested solution

This is a nice to have. The regex thing is something to we should look into as well. 

### Additional context

We should also look into getting their contributions indexed when we go live on monday https://insights.opensauced.pizza/user/yharaskrik/contributions

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by diivi**
## Description
Fixes #948 

I have tested with my timezone only, so testing is welcome.

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
#948 

## Mobile & Desktop Screenshots/Recordings
image

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by bdougie** [comment]
@open-sauced/triage could you try this out

**Comment by a0m0rajab** [comment]
Just a minor thing, could we change this line in the PR: 

https://github.com/open-sauced/insights/blob/0cedccc612c5080df3552e9d62580c540a4ac9c9/pages/start.tsx#L273

to have it as: 
```js
 const [currentLoginStep, setCurrentLoginStep] = useState<LoginSteps>(1); 
```

This will make the QA test easier without cloning the repo, we could go with this link to check it: 
https://deploy-preview-1488--oss-insights.netlify.app/start

**Comment by a0m0rajab** [comment]
# test: 
- changed the line provided in the previous comment
- opened the localhost/start page 

https://github.com/open-sauced/insights/assets/18273833/898e3e78-a753-4cbe-8a57-ce532c4417de

**Review by bdougie — APPROVED** [review]
tested on my second account and works for PST.

**Review by NsdHSO — APPROVED** [review]
LGTM

**Review by babblebey — COMMENTED** [review]
🍕

**Review by brandonroberts — APPROVED** [review]

**Pull request merged**
