### PR TITLE
feat: connect repositories to API

### LINKED ISSUE #850: Refractor: Move `/hub/insights/*` to its own route directory
### Type of feature

🧑‍💻 Refactor

### Current behavior

Currently the insights routes are all part of the `[filterName]` route, but in the insights case, the `[filterName]` value is always "hub", and it doesn't actually have a usage. This just causes a big unneeded confusion as to where the `hub/insights` route is on the developer's side.

### Suggested solution

Make a new root route in pages directory that is `hub` and move all insight routes to it.

Ex:
```
pages \
     hub \
          insights \
          ...
```

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by brandonroberts**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

This PR:
- Connects repositories to the API
- Removes repository hooks that are no longer used

## Related Tickets & Documents

Closes #850 

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Review by bdougie — APPROVED** [review]
LGTM

**Review by NsdHSO — COMMENTED** [review]
LGTM

**Review by OgDev-01 — APPROVED** [review]
🍕 🍕

**Review by Deadreyo — APPROVED** [review]
I guess you disabled the eslint rule that screams an error when you use the naming case of "something_something" like "full_name" ?

**Comment by brandonroberts** [comment]
> I guess you disabled the eslint rule that screams an error when you use the naming case of "something_something" like "full_name" ?

Yes, lower snake case is very common with APIs. In my opinion we don't need to do all the case switching from that standpoint

**Review by 0-vortex — APPROVED** [review]
LGTM! 👍

**Pull request merged**
