### PR TITLE
fix: improve general responsiveness of the Highlights page

### LINKED ISSUE #1336: Bug: General Responsiveness of the Highlights Page
### Describe the bug

General Responsiveness on the Highlights Page Isn't Crisp, some content goes out of the viewport and certain width size and some overflow on the x-axis is scrolled at some point too

screencast-insights opensauced pizza-2023 07 07-00_18_44

### Steps to reproduce

1. Go to https://insights.opensauced.pizza/feed
2. Restore you browser and reduce the width size to the smallest possible
3. Pay attention to how the viewport treats the content

### Browsers

Chrome

### Additional context (Is this in dev or production?)

Dev and Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by Shivam7-1**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

This modification will ensure that the content inside the HighlightsFilterCard component is contained within an overflow container that allows horizontal scrolling when necessary and limits the maximum width to prevent overflow.

It will solve the General responsiveness of the Highlights page. 
## Related Tickets & Documents

Fixes #1336 
## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by NsdHSO** [comment]
Hi @Shivam7-1  welcome to the community, could you check this [specs](https://www.conventionalcommits.org/en/v1.0.0/), your title should be `fix: general responsiveness of the highlights page`, Tnx again for your PR.

**Comment by babblebey** [comment]
Hi @Shivam7-1, while you try to correct the PR title as stated by @NsdHSO, do add a before and after screenshots or screencast/video that demos the solution.

**Comment by babblebey** [comment]
Hey @Shivam7-1 

I will assume you already have fork of the repo on your profile and it's cloned on your computer.

Start by Updating this branch in your fork, and re-pull it onto your computer.

> Hint
> 
> `git pull`

Then Follow the steps below.

- Open the project i.e. 'insights' in VSCode
- Look for the `node_modules` folder, if you find it within your folder structure, **delete it**, if you cannot find it, ignore this step.
- Open a new Terminal from VSCode 'Terminal' menu
- Run the command `npm ci` and wait for the process to complete.
- Then Run `npm run dev`

That should be everything.

Kindly Note: This Instruction assumes you already have NodeJS installed on your computer. If not, download NodeJS.

**Comment by Shivam7-1** [comment]
> Hey @Shivam7-1
> 
> I will assume you already have fork of the repo on your profile and it's cloned on your computer.
> 
> Start by Updating this branch in your fork, and re-pull it onto your computer.
> 
> > Hint
> > `git pull`
> 
> Then Follow the steps below.
> 
> * Open the project i.e. 'insights' in VSCode
> * Look for the `node_modules` folder, if you find it within your folder structure, **delete it**, if you cannot find it, ignore this step.
> * Open a new Terminal from VSCode 'Terminal' menu
> * Run the command `npm ci` and wait for the process to complete.
> * Then Run `npm run dev`
> 
> That should be everything.
> 
> Kindly Note: This Instruction assumes you already have NodeJS installed on your computer. If not, download NodeJS.

Hii @babblebey  I had Tryied above steps but i encountered Error After Performing `npm ci` Command and Then i am getting This Error
Screenshot 2023-07-12 191507

Is There any solution Could you Recommend to Resolve above Error

**Comment by bdougie** [comment]
@Shivam7-1 what node version are you running. Can you share more details about your environment?

**Comment by Shivam7-1** [comment]
> @Shivam7-1 what node version are you running. Can you share more details about your environment?

Hii I am using VS Code editor and Node.js Latest LTS Version: 18.16.1

**Comment by bdougie** [comment]
Linux?

**Comment by Shivam7-1** [comment]
> Linux?

Windows 11

**Comment by brandonroberts** [comment]
@Shivam7-1 run `npm run format` to apply formatting and fix the merge conflict. You can push that up to fix the PR preview while getting your environment issues figured out

**Comment by Shivam7-1** [comment]
> Hey @Shivam7-1
> 
> I will assume you already have fork of the repo on your profile and it's cloned on your computer.
> 
> Start by Updating this branch in your fork, and re-pull it onto your computer.
> 
> > Hint
> > `git pull`
> 
> Then Follow the steps below.
> 
> * Open the project i.e. 'insights' in VSCode
> * Look for the `node_modules` folder, if you find it within your folder structure, **delete it**, if you cannot find it, ignore this step.
> * Open a new Terminal from VSCode 'Terminal' menu
> * Run the command `npm ci` and wait for the process to complete.
> * Then Run `npm run dev`
> 
> That should be everything.
> 
> Kindly Note: This Instruction assumes you already have NodeJS installed on your computer. If not, download NodeJS.

Hii I had Try  after Re-install node.js again But Now i am getting this error I had attached Screen Recording of Error

https://github.com/open-sauced/insights/assets/55046031/8df91d69-ebec-4349-bed8-a1269fee6cdd

Can You please provide Solution if any

**Comment by babblebey** [comment]
> Hii I had Try after Re-install node.js again But Now i am getting this error I had attached Screen Recording of Error `PS C:\Users\user\Downloads\insights-beta\insights-beta> npm ci npm info using npm@9.5.1 npm info using node@v18.16.1 npm WARN cleanup Failed to remove some directories [ npm WARN cleanup [ npm WARN cleanup 'C:\\Users\\user\\Downloads\\insights-beta\\insights-beta\\node_modules\\@cspotcode', npm ERR! network This is a problem related to network connectivity. npm ERR! network In most cases you are behind a proxy or have bad network settings. npm ERR! network npm ERR! network If you are behind a proxy, please make sure that the npm ERR! network 'proxy' config is set properly. See: 'npm help config'`
> 
> Can You please provide Solution if any

Hi @Shivam7-1 

This error is as a result of your Internet connectivity, do try again with a stronger internet connection.

**Comment by Shivam7-1** [comment]
Hii @babblebey  Thanks Now it worked and I am able to run locally
And I would like close this PR will Create New PR as I have old Codebase and above PR no need to merge

**Comment by babblebey** [comment]
Great stuff @Shivam7-1 

Go on and do this! Do not forget to follow the current title structure when writing the title for your PR.

In fact, I'd suggest that you just copy and use the current PR title as is for the new PR.

Let's go ✊🏾

**Comment by Shivam7-1** [comment]
> Great stuff @Shivam7-1
> 
> Go on and do this! Do not forget to follow the current title structure when writing the title for your PR.
> 
> In fact, I'd suggest that you just copy and use the current PR title as is for the new PR.
> 
> Let's go ✊🏾

Yes done here it is https://github.com/open-sauced/insights/pull/1361

**Pull request closed without merging**
