### PR TITLE
feat: add `#100DayOfOSS` challenge anouncement to feeds

### LINKED ISSUE #1388: feat: AnnouncementCard
While you are waiting on reviews for #1381 @OgDev-01, can you implement this card with the 100days of OSS copy from the tweet announcement.

Screen Shot 2023-07-18 at 10 54 17 AM

Needs to go live by Friday.

## Copy 

Link to DEV post - https://dev.to/opensauced/100daysofoss-growing-skills-and-real-world-experience-3o5k
Copy:

> Join us for 100 days of supporting, sharing knowledge, and exploring the open source ecosystem together.

## Image
image

### PR DESCRIPTION
**Pull request by OgDev-01**
## Description
This PR adds the open-sauced `#100DaysOfOSS` challenge announcement to the feeds page and updates component naming, props and styles to fit its use.

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
Closes #1388 

## Mobile & Desktop Screenshots/Recordings

image

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by bdougie** [comment]
Can darken the image. Either use this, or add a black square with 10% opacity. Finding the white contrast with the site's grey hard to look at.

Group 9

**Comment by OgDev-01** [comment]
This still doesn't look quite ok to me
image

**Comment by bdougie** [comment]
> This still doesn't look quite ok to me image

Let's just role with the original and perhaps get @chhristopher to create to something else later. Probably just one light mode friendly.

**Review by bdougie — APPROVED** [review]

**Comment by chhristopher** [comment]
@bdougie @OgDev-01  agreed, i'll look into having something that plays nice with everything else on the page

**Pull request merged**
