### PR TITLE
fix: fix for empty repo list

### LINKED ISSUE #777: Bug: broken avatar when no results on page
### Describe the bug

The insights page is showing broken avatar when no results are present on the page. 
image

### Steps to reproduce

1. Go to https://insights.opensauced.pizza/kotlin/repositories
2. Filter based on Most Spammed 
3. Broken avatar shows on the row.
image

### Affected services

insights.opensauced.pizza

### Platforms

Desktop

### Browsers

Chrome

### Environment

Production

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by SimranjitKaurMaan**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [X] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
Fixes #777 

Fixes the repo table when the repo list is empty.

## Mobile & Desktop Screenshots/Recordings
Before fix: The repo list is empty so repo table shows broken avatar and no data row.

image

After fix: The repo table has 0 rows as repo list is empty.
image

## Added tests?

- [ ] 👍 yes
- [X] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Review by bdougie — APPROVED** [review]
We will need to add a design for an empty list or no results found, but this works for now.

**Comment by SimranjitKaurMaan** [comment]
Thanks @bdougie for reviewing the PR. can any maintainer help merging this PR then?

**Comment by SimranjitKaurMaan** [comment]
> We will need to add a design for an empty list or no results found, but this works for now.

I will create a issue to track the design requirement.

**Review by OgDev-01 — APPROVED** [review]
Thanks for taking your time and making this contribution 🍕

**Comment by bdougie** [comment]
@SimranjitKaurMaan would be able to create a highlight about your work on this fix?

https://opensauced.pizza/blog/social-coding-is-back

**Pull request merged**
