### PR TITLE
fix: single highlight dialog close button not working in new browser tab

### LINKED ISSUE #1544: Bug: Single Highlight Dialog Close Button not Working in new Browser Tab
### Describe the bug

When clicking a single highlight link from an external webpage, the close button within the dialog does not respond as expected to the close action. The issue can be traced back to a specific code block within the repository:

[Link to the Code Block](https://github.com/open-sauced/insights/blob/a7b0c3bb95e76e2d0e700265ac405e8a71b3c97a/pages/feed/index.tsx#L163)

This problem appears to stem from the routing behaviour of the application. When the router attempts to route to a specific page, it fails to do so when the page is opened in a new tab. This is because there are no browsing history entries to navigate back to in the new tab instance.

### Proposed Solution

To address this issue, we need to consider the routing behaviour when allowing the dialog to close and route to the `/feed` page. The current condition for closing the dialog may need to be modified to account for scenarios where the page was opened in a new tab. By factoring in this behaviour, we can ensure that the dialog behaves as expected even when accessed through external highlight links.

### Steps to reproduce

https://github.com/open-sauced/insights/assets/106407013/b9051be5-2694-4265-abd6-90f2a6daed7c

### Browsers

Chrome

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by babblebey**
## Description

This Pull Request improves the conditional routing on the Single Highlight Dialog Close action, extending the feature introduced in #1473 by factoring in the case when a user clicks on a single highlight from an **_external URL_**.

### Changes Made 

- added a `shouldAllowDialogCloseAction` boolean value that checks the following conditions to determine whether a simple dialog close action should be allowed
  - `props.referer` is `null` i.e. the single highlight (`/feed/[id]`) route was visited via a direct url input to the browser tab.
  - `typeof props.referer` is `string` and `!props.referer.includes(host)` i.e. the single highlight (`/feed/[id]`) route was visited via a click from an external website.
  - `typeof props.referer` is `string` and `props.referer === ${host}/feed` i.e. the single highlight (`/feed/[id]`) route was visited from the `/feed`s page

**Implementation**
```js
const shouldAllowDialogCloseAction =
  props.referer === null ||
  (typeof props.referer === "string" && !props.referer.includes(host)) ||
  (typeof props.referer === "string" && props.referer === `${host}/feed`);
```

- replace `Dialog` component close button conditions with `shouldAllowDialogCloseAction`

```js
{shouldAllowDialogCloseAction ? (
  <DialogCloseButton ... />
) : (
  <Button ... />
)}
```

- replace `Dialog` component `onOpenChange` conditions with `shouldAllowDialogCloseAction`

```js
<Dialog
  open={openSingleHighlight}
  // onOpenChange action/prop
  onOpenChange={(open) => {
    if (openSingleHighlight && !open) {
      if (shouldAllowDialogCloseAction) {      // <- Logic starts here 🍕
        setOpenSingleHighlight(false);
        router.replace("/feed");
      } else {
        router.back();
      }     // <- ends here 🍕
    }
  }}
>
...
</Dialog>
```

🍕

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #1544

## Mobile & Desktop Screenshots/Recordings

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2023.08.12-15_34_13.webm](https://github.com/open-sauced/insights/assets/25631971/50f820c8-2c3c-4720-b061-bcccb850e64f)

## Added tests?

- [x] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?
NA

## [optional] What gif best describes this PR or how it makes you feel?
giphy

GUESS WHAT!? I WROTE A TEST

### CODE REVIEW

**Review by brandonroberts — APPROVED** [review]

**Comment by RitaDee** [comment]
Nice one @babblebey 
LGTM 🍕

**Review by jpmcb — APPROVED** [review]

**Comment by babblebey** [comment]
> Nice one babblebey 

Thanks.. Nice indeed it feels to write my first test 🍕

**Review by bdougie — APPROVED** [review]
@brandonroberts I think we can start requiring test for bug fixes moving forward. 

@babblebey curious if you'd be interested in writing a blog post about writing e2e using this test as example. We welcome it on the opensauced DEV - https://dev.to/opensauced

**Comment by babblebey** [comment]
> @brandonroberts I think we can start requiring test for bug fixes moving forward. 
> 
> @babblebey curious if you'd be interested in writing a blog post about writing e2e using this test as example. We welcome it on the opensauced DEV - https://dev.to/opensauced

Oh wow @bdougie 

I will gladly write my first blogpost to this effect.

I'll get a draft ready to run by you shortly. I'll take all the help I can get in terms of input.

**Pull request merged**
