### PR TITLE
feat: add microformats for user details

### LINKED ISSUE #814: Feature: Microformat SEO data per page
### Type of feature

🍕 Feature

### Current behavior

We are not making User profiles and Insight Pages friendly with SEO. 

related, https://github.com/open-sauced/insights/issues/687

### Suggested solution

Set up search engine enrichment data. Not sure what the solution is in next.js, but would love thoughts. 

Here is an article for Next.js - https://nextjs.org/learn/seo/introduction-to-seo

Context from Google - https://developers.google.com/search/docs/appearance/structured-data/search-gallery

### Additional context

cc @0-vortex 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by Deadreyo**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

Adds microformats for user details in user profile pages. Follows microformats 2 convention.

## Related Tickets & Documents

closes #814 

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Review by 0-vortex — CHANGES_REQUESTED** [review]
What we need is completely missing from this PR: https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data

**Comment by Deadreyo** [comment]
> What we need is completely missing from this PR: https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data

How so? I've implemented the structured data using microformats

**Comment by 0-vortex** [comment]
> > What we need is completely missing from this PR: https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data
> 
> How so? I've implemented the structured data using microformats

But that is not what the issue requires, the link in the issue has this screenshot on first page:

Screenshot 2023-02-16 at 22 40 05

The list of rich widget embeds that appear enhanced in the search results: https://developers.google.com/search/docs/appearance/structured-data/search-gallery

Clicking on javascript there is absolutely no integration to the json+ld requirement but something like https://github.com/google/react-schemaorg would do the trick.

Then, bare minimum is implementing a subset of `Person` schema: https://schema.org/Person

All the above can be referred to as "microformats", however the link issue describes json+ld rich schemas and embeds available in search engines! 🍕

**Comment by Deadreyo** [comment]
@0-vortex 
Same data structure can be achieved by microformats, which is an alternative to microdata, which is an alternative to json ld as described by google here
image

In my opinion microformats are much better for our dev environment and easier to integrate, especially with a lot of levels of components and possibly separate data fetching that can complicate the json ld.

I've tested microformats 1 on Google Test and it works
image
(ignore the errors)

But seems like microformats v2 is not supported so I'll need to add microformats v1.

**Comment by 0-vortex** [comment]
> In my opinion microformats are much better for our dev environment and easier to integrate, especially with a lot of levels of components and possibly separate data fetching that can complicate the json ld.

I hear you, however, the issues is to implement JSON+LD, which had been decided last month because it is the only one actually enhancing both the end user experience and our outreach.
Please move the target branch to alpha as discussed in the slack security concerns! 🍕

**Pull request closed without merging**
