### PR TITLE
fix: connect reports to the API

### PR DESCRIPTION
**Pull request by brandonroberts**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

- Uses the API to pull data for reports
- Fixes bugs with the current date and button alignment

## Mobile & Desktop Screenshots/Recordings

image

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Review by 0-vortex — APPROVED** [review]
LGTM! 👍

**Comment by brandonroberts** [comment]
> Is the screenshot in the PR a preview of before or after the alignment has been fixed?

After, this is the before:

image

**Comment by OgDev-01** [comment]
reports

A little bit of misalignment on the table

**Comment by bdougie** [comment]
Aside from the visual alignment, am I also checking to see if reports include data?

**Comment by brandonroberts** [comment]
@bdougie there likely won't be any data to show up on beta. We need to sync over some fresh data

**Comment by bdougie** [comment]
Of course. Keep forgetting that

**Review by bdougie — APPROVED** [review]

**Comment by brandonroberts** [comment]
Better table alignment

image

**Review by OgDev-01 — APPROVED** [review]
LGTM

**Pull request merged**
