### PR TITLE
feat: Link repos to GitHub

### LINKED ISSUE #620: feature: Link back to GitHub
### Type of feature

Select the type of feature request, the lowercase should also be the PR prefix.

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

### Current behavior

We need to start linking to GitHub and tracking bounces. I will work starting to segment things via PostHog, but the below links need to be added

### Suggested solution

Describe the solution you'd like.

~~1. Link to GitHub Profiles every there is an avatar (not the user profile and keep in mind hovercards will also have a link). We will remove this when User profiles ship and instead link there~~
- [ ] #669
- [ ] #670
 
### Code of Conduct

By submitting this issue, you agree to follow our [Code of Conduct](https://docs.opensauced.pizza/contributing/code-of-conduct/).

- [x] I agree to follow this project's Code of Conduct

### Contributing Docs

If you plan on contributing code please read - [Contribution Guide](https://docs.opensauced.pizza/contributing/introduction-to-contributing/)

- [x]  I agree to follow this project's Contribution Docs

### LINKED ISSUE #669: feat: Link to contribution and PRs. Right now we list contributions on the contributor page. We will need to link to that PR.
The link to the PR should be clickable in this red box. This needs an update in the API.

Screen Shot 2022-12-16 at 11 17 02 AM

### LINKED ISSUE #670: feat: Link to repo dashboard. In the future, we will want to create repo pages, but for now link to GitHub.
Link to the repo should be clickable in this red box. 
Screen Shot 2022-12-16 at 11 15 01 AM

### PR DESCRIPTION
**Pull request by Deadreyo**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

This PR links user profiles in Contributors tab to their GitHub profiles, links repositories avatars in Repositories tabs to their Github pages, and links PRs to their github links. Visual context is provided below.

Modified the PR data interface to include the new/required data fields coming from the backend.

Also added these new fields to the storybook tests.

Linked with the backend issue: https://github.com/open-sauced/gs-api.opensauced.pizza/issues/116

## Related Tickets & Documents

closes #670 
closes #620 
closes #669 

## Mobile & Desktop Screenshots/Recordings

image
image
image

## Added tests?

- [x] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by bdougie** [comment]
@Deadreyo, can we focus this PR on what can ship and leave the rest for a future PR.

**Comment by Deadreyo** [comment]
> @Deadreyo, can we focus this PR on what can ship and leave the rest for a future PR.

The backend api endpoint has been updated an hour ago so the blocker has been removed. Should be finished by tomorrow

**Comment by bdougie** [comment]
> The backend api endpoint has been updated an hour ago so the blocker has been removed. Should be finished by tomorrow

Excellent. Thanks for following up on that. I went ahead create separate issues, but we can close them all out when this PR is merged.

**Comment by SunGoldTech** [comment]
run `npm run build` to check the errors @Deadreyo

**Comment by Deadreyo** [comment]
> run `npm run build` to check the errors @Deadreyo

No errors showing up

**Comment by Deadreyo** [comment]
Are these issues related to this PR belonging to a fork? I've merged my work into a branch in the original and can open a new PR if that was indeed the issue

**Review by bdougie — APPROVED** [review]

**Review by brandonroberts — APPROVED** [review]

**Pull request merged**
