### PR TITLE
fix: Auto-Scroll Not Triggered Upon Clicking 'Next Page' in Highlight…

### LINKED ISSUE #1386: Bug: Auto-Scroll Not Triggered Upon Clicking 'Next Page' in Highlights Page
### Describe the bug

Currently, when a user clicks the next page icon, the auto-scroll feature is not being activated on the new page. This results in the user being left at the same scroll position they were in on the previous page. This bug requires users to manually scroll back to the top of the page each time they navigate to a new page, which is not the intended behavior. Ideally, upon clicking the next page icon, the system should automatically scroll the user to the top of the new page to provide a seamless browsing experience.

Issue-Bug-

### Steps to reproduce

1. Go to [https://insights.opensauced.pizza/feed](https://insights.opensauced.pizza/feed)
2. Scroll down to the end of the page and click next page icon

### Browsers

Chrome, Safari

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by aryanas159**
…s Page

## Description

fixes #1386
Added a useRef and activated the scrollIntoView method when changing pages.
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI

https://github.com/open-sauced/insights/assets/114330931/35a6fbf9-7cda-473e-a70a-43ca6e0addad

- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by aryanas159** [comment]
.take

**Review by OgDev-01 — APPROVED** [review]
Thanks @aryanas159, LGTM 🍕

**Review by babblebey — APPROVED** [review]
LG 🍕

**Review by bdougie — APPROVED** [review]
Looks good, thanks for working on this.

**Pull request merged**
